name: Build Kivy APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install system deps
        run: |
          sudo apt update
          sudo apt install -y git zip unzip openjdk-17-jdk \
          python3-pip autoconf libtool pkg-config \
          zlib1g-dev libncurses-dev libffi-dev libssl-dev \
          automake

      - name: Install Android SDK + build-tools (FIX AIDL)
        run: |
          sudo apt update
          sudo apt install -y android-sdk adb sdkmanager || true

          # вручную докачиваем build-tools и platform-tools
          yes | sdkmanager --licenses || true
          sdkmanager "platform-tools" "platforms;android-33" "build-tools;33.0.2" || true

      - name: Install Buildozer
        run: |
          pip install --upgrade pip
          pip install buildozer cython==0.29.36 wheel setuptools==68.0.0

      - name: Fix environment paths
        run: |
          export ANDROID_HOME=/usr/lib/android-sdk
          export PATH=$PATH:$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools

      - name: Build APK
        run: buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: kivy-apk
          path: bin/*.apk
